### ISSUE TITLE
小姐姐，我提个问题

### ISSUE THREAD

**Issue by LGinC** [huxiaoman7/PaddlePaddle_code#2]
首先，我是新手，对于CNN完全不了解，对Python也只是知道一点点。
我以为第一篇手写数字识别很.....通俗，但是您这除了paddlepaddle的安装外，那堆源码让我一脸懵逼.......不知所云.......就希望能不能再基础点儿....
求领进门

**Comment by huxiaoman7** [comment]
不好意思啊，第一篇写的只是个试水的，当时没想着写三个月系列，就打算把平时用的总结下。现在决定了就打算好好写。下一篇详细讲讲手写数字识别的原理。以后写文章都会分为两个部分，先讲原理，然后讲代码，还有什么建议都可以提~
