### ISSUE TITLE
你好。

### ISSUE THREAD

**Issue by 447zyg** [huxiaoman7/PaddlePaddle_code#3]
刚接触机器学习
Python 2.7.14 (default, Nov  1 2017, 10:27:43) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle.v2 as paddle
>>>

paddlepaddle的安装导入都成功了。
但是一旦运行相关代码 就提示（初始化的时候就崩了）
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
能指点个方向吗。

机子是mac
系统自带的python是2.7.10 
（自带的install paddle安不上去。百度说要关SIP我就没考虑了。。）
装的2.7.14
非常感谢!

**Comment by 447zyg** [comment]
好吧   还是选择了暂时关闭sip。重新安装paddle后再打开。（结果是绕过去了2333）

**Comment by huxiaoman7** [comment]
恩，我没有遇到过这个问题诶，建议去paddle下面提个issue看有没有解决方法？
